version: '2.1'
services:
  zookeeper:
    env_file:
      - ./.env
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    env_file:
      - ./.env
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '9093:9093'

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    env_file:
      - ./.env
    ports:
      - 8082:8080
    depends_on:
      - kafka